# Generated by Django 5.2.8 on 2025-11-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviciosproyecto_obra_estado_obra_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.proyecto', verbose_name='Proyecto'),
        ),
    ]
