# Generated by Django 5.2.8 on 2025-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_serviciosproyecto_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_proyecto',
            field=models.CharField(choices=[('proceso', 'Proceso'), ('realizado', 'Realizado')], default='proceso', max_length=20, verbose_name='Estado'),
        ),
    ]
