# Generated by Django 5.2.8 on 2025-11-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_principal', models.CharField(max_length=100, verbose_name='Categoria Principal')),
                ('subcategoria', models.CharField(max_length=100, verbose_name='Subcategoria')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CatalogoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo o N° de Parte')),
                ('nombre_completo_producto', models.CharField(max_length=300, verbose_name='Nombre Completo')),
                ('descripcion_funcional', models.TextField(blank=True, null=True, verbose_name='Descripcion Funcional')),
                ('url_ficha_tecnica', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ficha Tecnica (URL)')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca', verbose_name='Marca')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Dispositivo de Catalogo',
                'verbose_name_plural': 'Dispositivos de Catalogo',
            },
        ),
    ]
