# Generated by Django 5.2.8 on 2025-11-10 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoria_catalogodispositivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanciaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_dispositivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='TAG (Ej: REL-TAB-01)')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=200, null=True, verbose_name="Ubicacion Fisica (Ej: 'Sala de Control', 'Patio')")),
                ('atributos', models.JSONField(blank=True, default=dict, verbose_name='Atributos (IP, Rango, etc.)')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='core.catalogodispositivo', verbose_name='Dispositivo del Catalogo')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
            ],
            options={
                'verbose_name': 'Instancia de Dispositivo',
                'verbose_name_plural': 'Instancias de Dispositivos',
            },
        ),
    ]
