# Generated by Django 5.2.8 on 2025-11-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_instanciadispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name="instanciadispositivo",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.proyecto",
                verbose_name="Proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="instanciadispositivo",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.proyecto",
                verbose_name="Proyecto",
            ),
        ),
    ]
