# Generated by Django 5.2.8 on 2025-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_proyecto_to_instancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciadispositivo',
            name='ubicacion_fisica',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Ubicacion Fisica"),
        ),
    ]
