# Generated by Django 5.2.8 on 2025-11-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_instanciadispositivo_ubicacion_fisica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_funcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo de Funcion (Ej: 50/51, 87)')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Funcion')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Funcion de Dispositivo',
                'verbose_name_plural': 'Funciones de Dispositivos',
                'ordering': ['codigo_funcion', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='instanciadispositivo',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='catalogodispositivo',
            name='funciones_soportadas',
            field=models.ManyToManyField(blank=True, to='core.funciondispositivo', verbose_name='Funciones Soportadas (de fabrica)'),
        ),
        migrations.AddField(
            model_name='instanciadispositivo',
            name='funciones_usadas',
            field=models.ManyToManyField(blank=True, to='core.funciondispositivo', verbose_name='Funciones Usadas (en este proyecto)'),
        ),
    ]
