# Generated by Django 5.2.8 on 2025-11-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_funciondispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogodispositivo',
            name='especificaciones',
            field=models.JSONField(blank=True, default=dict, verbose_name='Especificaciones (Potencia, Fase, etc.)'),
        ),
    ]
