# Generated by Django 5.2.8 on 2025-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_catalogodispositivo_especificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Atributo')),
                ('unidad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('tipo_dato', models.CharField(choices=[('str', 'Cadena'), ('int', 'Entero'), ('dec', 'Decimal'), ('bool', 'Booleano')], max_length=10, verbose_name='Tipo de Dato')),
            ],
            options={
                'verbose_name': 'Atributo Maestro',
                'verbose_name_plural': 'Atributos Maestro',
                'ordering': ['nombre'],
            },
        ),
    ]
