# Generated by Django 5.2.8 on 2025-11-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_atributomaestro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogodispositivo',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='instanciadispositivo',
            name='atributos',
        ),
        migrations.CreateModel(
            name='AtributoInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.atributomaestro')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_set', to='core.instanciadispositivo')),
            ],
            options={
                'unique_together': {('instancia', 'atributo')},
            },
        ),
        migrations.CreateModel(
            name='EspecificacionCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.atributomaestro')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones_set', to='core.catalogodispositivo')),
            ],
            options={
                'unique_together': {('catalogo', 'atributo')},
            },
        ),
    ]
