# Generated by Django 5.2.8 on 2025-11-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_catalogodispositivo_especificaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogodispositivo',
            name='atributos_sugeridos',
            field=models.ManyToManyField(blank=True, related_name='catalogos_sugeridos', to='core.atributomaestro', verbose_name='Atributos Variables (Plantilla)'),
        ),
    ]
