# Generated by Django 5.2.8 on 2025-11-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_catalogodispositivo_atributos_sugeridos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributomaestro',
            name='tipo_dato',
        ),
        migrations.RemoveField(
            model_name='catalogodispositivo',
            name='atributos_sugeridos',
        ),
    ]
