# Generated by Django 5.2.8 on 2025-11-28 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_atributomaestro_tipo_dato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
    ]
