# Generated by Django 5.2.8 on 2025-12-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_obra_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciadispositivo',
            name='tag_dispositivo',
        ),
    ]
