# Generated by Django 5.2.8 on 2025-12-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_drop_catalogodispositivo_atributos_sugeridos'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='obra',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia/Estado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección / Calle'),
        ),
    ]
