# Generated by Django 5.2.8 on 2026-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_instanciainstancia_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogodispositivo',
            name='precio_historico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Historico (USD/Referencia)'),
        ),
        migrations.AddField(
            model_name='instanciadispositivo',
            name='precio_real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Real (Compra/Cotizado)'),
        ),
    ]
