# Generated by Django 5.2.8 on 2026-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_catalogodispositivo_precio_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogodispositivo',
            name='precio_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Actual de Mercado (USD)'),
        ),
        migrations.AlterField(
            model_name='catalogodispositivo',
            name='precio_historico',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Historico (USD/Ref)'),
        ),
    ]
