# Generated by Django 5.2.8 on 2026-01-27 13:53

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_catalogodispositivo_precio_actual_and_more'),
    ]

    operations = [
        # Cliente
        migrations.AddField(
            model_name='cliente',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),

        # Marca
        migrations.AddField(
            model_name='marca',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AddField(
            model_name='marca',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),

        # Categoria
        migrations.AddField(
            model_name='categoria',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AddField(
            model_name='categoria',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),

        # CatalogoDispositivo
        migrations.AddField(
            model_name='catalogodispositivo',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AddField(
            model_name='catalogodispositivo',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='catalogodispositivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogodispositivo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),

        # FuncionDispositivo
        migrations.AddField(
            model_name='funciondispositivo',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AddField(
            model_name='funciondispositivo',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='funciondispositivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funciondispositivo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),

        # InstanciaDispositivo
        migrations.AlterField(
            model_name='instanciadispositivo',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AddField(
            model_name='instanciadispositivo',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='instanciadispositivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instanciadispositivo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),

        # Obra
        migrations.AlterField(
            model_name='obra',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AddField(
            model_name='obra',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),

        # Proyecto
        migrations.AlterField(
            model_name='proyecto',
            name='usuario_creador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_creados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Creado por',
            ),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario_modificador',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='%(class)s_modificados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Modificado por',
            ),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now, verbose_name='Ultima Modificacion'),
            preserve_default=False,
        ),
    ]
